# Default language (English)

toc:
  title: Contents

pagination:
  prev: Previous
  next: Next

page:
  published_at: Published on
  untitled: Untitled
  comments: Comments
  archives:
    title: Archives
  categories:
    title: Categories
  tags:
    title: Tags

widget:
  author: Author
  recent_posts: Recent Posts
  categories: Categories
  tags: Tags
  archives:
    title: Archives
    month_format: "{year}-{month}"
    unit: " articles"

aside:
  articles: Articles
  tags: Tags
  categories: Categories

search:
  title: Search
  placeholder: Search...

recommend:
  title: Recommended
